# Generated by Django 5.1.5 on 2025-02-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0003_remove_farm_date_joined_remove_farm_first_name_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='type',
            name='farm',
        ),
    ]
