# Generated by Django 5.1.5 on 2025-02-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0004_remove_farm_date_joined_remove_farm_first_name_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('Sold', 'Sold'), ('Slaughtered', 'Slaughtered'), ('Stolen', 'Stolen'), ('Lost', 'Lost'), ('Unknown', 'Unknown'), ('Sick', 'Sick')], default='Alive', max_length=40),
        ),
    ]
